import { CollectionItem } from '../components/Collection/Collection.types';

export const CollectionData: CollectionItem[] = [
  {
    title: 'Septimius Severus Denarius',
    imgPath: 'Images/Collection/SeptimiusSeverusDenarius.webp',
    ruler: 'Septimius Severus (193-211 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '210 AD',
    obverseDescription: 'Diademed bust of Severus facing right. "SEVERUS PIVS AVG"',
    reverseDescription:
      'Jupiter, naked, holding thunderbolt and sceptre. Two children flanking representing Severus\' sons Caracalla and Geta. "PM TRP XVIII COS III PP"',
    catalogueNumber: 'RIC IV #233',
  },
  {
    title: 'Julia Domna Denarius',
    imgPath: 'Images/Collection/JuliaDomnaDenarius.webp',
    ruler: 'Caracalla (198-217 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '211-217 AD',
    obverseDescription: 'Bust of Julia Domna, draped, facing right. "IVLIA PIA FELIX AVG"',
    reverseDescription: 'Vesta, standing left holding Palladium and sceptre. "VESTA"',
    catalogueNumber: 'RIC IV #390',
  },
  {
    title: 'Geta Denarius',
    imgPath: 'Images/Collection/GetaDenarius.webp',
    ruler: 'Septimius Geta (209-211 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '203-208 AD',
    obverseDescription: 'Bust of Geta facing right. "P SEPTIMIVS GETA CAES"',
    reverseDescription:
      'Providentia, draped, standing left, holding wand over globe and sceptre. "PROVID DEORVM"',
    catalogueNumber: 'RIC IV.1 #51',
  },
  {
    title: 'Caracalla Denarius',
    imgPath: 'Images/Collection/CaracallaDenarius.webp',
    ruler: 'Caracalla (198-217 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '214 AD',
    obverseDescription: 'Diademed bust of Caracalla facing right. "ANTONINVS PIVS AVG GERM"',
    reverseDescription:
      'Apollo, shirtless, seated left, holding olive branch and leaning on lyre. "PM TRP XVII COS IIII PP"',
    catalogueNumber: 'RIC IV #238A',
  },
  {
    title: 'Elagabalus Denarius',
    imgPath: 'Images/Collection/Elagabalus.webp',
    ruler: 'Elagabalus (218-222 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '218-222 AD',
    obverseDescription:
      'Diademed and cuirassed bust of Elagabalus facing right. "IMP CAES ANTONINVS AVG"',
    reverseDescription: 'Victory advancing right with wreath and trophy. "VICTOR ANTONINI AVG"',
    catalogueNumber: 'RIC IV.2 #153',
  },
  {
    title: 'Constantine I Nummus',
    imgPath: 'Images/Collection/ConstantineNummus.webp',
    ruler: 'Constantine I "The Great" (306-337 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '307-337 AD',
    obverseDescription:
      'Diademed and cuirassed bust of Constantine facing right. "CONSTANTINVS MAX AVG"',
    reverseDescription:
      'Two military standards, flanked by a soldier on each side. Mint mark "RBP" in exergue. "GLORIA EXERCITVS"',
    catalogueNumber: 'RIC VII #335',
  },
  {
    title: 'Alexander The Great Diobol',
    imgPath: 'Images/Collection/AlexanderDiobol.webp',
    ruler: 'Alexander III "The Great" (336-323 BC)',
    authority: 'Kingdom of Macedon',
    mintLocation: 'Kaunos, Karia',
    mintDate: '300-200 BC',
    obverseDescription: 'Diademed bust of Alexander III "The Great"',
    reverseDescription: 'Two cornucopiae bound together. "K A"',
    catalogueNumber: 'SNG Helsinki I #76',
  },
  {
    title: 'Septimius Severus Denarius',
    imgPath: 'Images/Collection/SeverusSalusDenarius.webp',
    ruler: 'Septimius Severus (193-211 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '197-198 AD',
    obverseDescription: 'Diademed bust of Severus facing right. "L SEPT SEV PERT AVG IMP X"',
    reverseDescription:
      'Salus, seated left, feeding serpent on an altar from a patera. "SALVTI AVGG"',
    catalogueNumber: 'RIC IV #119A',
  },
  {
    title: 'Claudius As',
    imgPath: 'Images/Collection/ClaudiusAs.webp',
    ruler: 'Claudius (41-50 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '41-50 AD',
    obverseDescription: 'Bust of Claudius facing left. "TI CLAVDIVS CAESAR AVG PM TRP IMP"',
    reverseDescription: 'Libertas, draped, holding pileus in right hand. "LIBERTAS AVGVSTA SC"',
    catalogueNumber: 'RIC I #97',
  },
  {
    title: 'Constantius II Nummus',
    imgPath: 'Images/Collection/ConstantiusIINummus.webp',
    ruler: 'Constantius II (337-361 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Nicomedia',
    mintDate: '348-350 AD',
    obverseDescription: 'Diademed bust of Constantius II facing right. "DN CONSTANTIVS PFG AVG"',
    reverseDescription:
      'Soldier with spear lunging over barbarian on horseback. "FEL TEMP REPARATIO"',
    catalogueNumber: 'RIC VIII #189',
  },
  {
    title: 'William III Shilling',
    imgPath: 'Images/Collection/WilliamIIIShilling.webp',
    ruler: 'William III (1689-1702 AD)',
    authority: 'United Kingdom',
    mintLocation: 'England',
    mintDate: '1696 AD',
    obverseDescription: 'Bust of William III facing right. "GVLIELMVS III DEI GRA"',
    reverseDescription:
      'Crowned shields of each kingdom of the union (Britain, France and Ireland) around central Nassau Lion. "MAG BR FRA ET HIB REX 1696"',
    catalogueNumber: 'KM #485.1',
  },
  {
    title: 'Aurelian Antoninianus',
    imgPath: 'Images/Collection/AurelianAntoninianus.webp',
    ruler: 'Aurelian (270-275 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Rome',
    mintDate: '270-275 AD',
    obverseDescription: 'Crowned Aurelian facing right, "IMP CL DOM AVRELIANVS AVG"',
    reverseDescription:
      'Securitas, standing with legs crossed, holding sceptre and leaning on column. "XI" (denomination) to right. "SECURITAS AVG"',
    catalogueNumber: 'RIC V #38',
  },
  {
    title: 'Constantine I Nummus',
    imgPath: 'Images/Collection/ConstantineCampGates.webp',
    ruler: 'Constantine I "The Great" (306-337 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Nicomedia',
    mintDate: '324-329 AD',
    obverseDescription: 'Diademed bust of Constantine. "CONSTANTIVS AVG"',
    reverseDescription:
      'Military camp gates with 2 towers either side, and a star above. "NB" mint mark in exergue. "PROVIDENTIA AVGG"',
    catalogueNumber: 'RIC VII #90',
  },
  {
    title: 'Constans Nummus',
    imgPath: 'Images/Collection/ConstansNummus.webp',
    ruler: 'Constans (337-350 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Constantinople',
    mintDate: '336-337 AD',
    obverseDescription: 'Diademed bust of Constans facing left. "FL CONSTANS NOB CAES"',
    reverseDescription:
      'Military standard flanked by two cuirassed soldiers with spears. "CONS" mint mark in exergue. "GLORIA EXERCITVS"',
    catalogueNumber: 'RIC VII #140',
  },
  {
    title: 'Valentinian I Nummus',
    imgPath: 'Images/Collection/ValentinianVictory.webp',
    ruler: 'Valentinian I (364-375 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Siscia',
    mintDate: '364-367 AD',
    obverseDescription: 'Diademed bust of Valentinian facing right. "DN VALENTINIANVS PF AVG"',
    reverseDescription:
      'Victory advancing left, holding wreath. "*A" mint mark left of Victory. "DΔSISC" mint mark in exergue. "SECVRITAS REIPVBLICAE"',
    catalogueNumber: 'RIC IX #7A',
  },
  {
    title: 'Valentinian I Nummus',
    imgPath: 'Images/Collection/ValentinianCaptive.webp',
    ruler: 'Valentinian I (364-375 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Siscia',
    mintDate: '364-375 AD',
    obverseDescription: 'Diademed bust of Valentinian facing right. "DN VALENTINIANVS PF AVG"',
    reverseDescription:
      'Military-dressed emperor advancing right, holding labarum and dragging captive. "BSISC" mint mark in exergue. "GLORIA ROMANORVM"',
    catalogueNumber: 'RIC IX #14A',
  },
  {
    title: 'Valentinian II Nummus',
    imgPath: 'Images/Collection/ValentinianIINummus.webp',
    ruler: 'Valentinian II (375-392 AD)',
    authority: 'Roman Empire',
    mintLocation: 'Aquileia',
    mintDate: '378-388 AD',
    obverseDescription: 'Diademed bust of Valentinian facing right. "DN VALENTINIANVS PF AVG"',
    reverseDescription: 'Wreath containing text. "SMAQ" mint mark in exergue. "VOT X MVLT XX"',
    catalogueNumber: 'RIC IX #19',
  },
];
