import { Leader, LeaderName, LeaderType } from '../shared/types/Leader.types';

export const LeaderData: Leader[] = [
  {
    name: LeaderName.ConstantiusII,
    type: LeaderType.Ruler,
    reign: '337-361 AD',
    url: 'https://en.wikipedia.org/wiki/Constantius_II',
  },
  {
    name: LeaderName.Constans,
    type: LeaderType.Ruler,
    reign: '337-350 AD',
    url: 'https://en.wikipedia.org/wiki/Constans',
  },
  {
    name: LeaderName.ValentinianII,
    type: LeaderType.Ruler,
    reign: '375-392 AD',
    url: 'https://en.wikipedia.org/wiki/Valentinian_II',
  },
  {
    name: LeaderName.ConstantineITheGreat,
    type: LeaderType.Ruler,
    reign: '306-337 AD',
    url: 'https://en.wikipedia.org/wiki/Constantine_the_Great',
  },
  {
    name: LeaderName.AlexanderIIITheGreat,
    type: LeaderType.Ruler,
    reign: '336-323 BC',
    url: 'https://en.wikipedia.org/wiki/Alexander_the_Great',
  },
  {
    name: LeaderName.SeptimiusSeverus,
    type: LeaderType.Ruler,
    reign: '193-211 AD',
    url: 'https://en.wikipedia.org/wiki/Septimius_Severus',
  },
  {
    name: LeaderName.Caracalla,
    type: LeaderType.Ruler,
    reign: '198-217 AD',
    url: 'https://en.wikipedia.org/wiki/Caracalla',
  },
  {
    name: LeaderName.Claudius,
    type: LeaderType.Ruler,
    reign: '41-50 AD',
    url: 'https://en.wikipedia.org/wiki/Claudius',
  },
  {
    name: LeaderName.ValentinianI,
    type: LeaderType.Ruler,
    reign: '364-375 AD',
    url: 'https://en.wikipedia.org/wiki/Valentinian_I',
  },
  {
    name: LeaderName.Geta,
    type: LeaderType.Ruler,
    reign: '209-211 AD',
    url: 'https://en.wikipedia.org/wiki/Geta_(emperor)',
  },
  {
    name: LeaderName.WilliamIII,
    type: LeaderType.Ruler,
    reign: '1689-1702 AD',
    url: 'https://en.wikipedia.org/wiki/William_III_of_England',
  },
  {
    name: LeaderName.Aurelian,
    type: LeaderType.Ruler,
    reign: '270-275 AD',
    url: 'https://en.wikipedia.org/wiki/Aurelian',
  },
  {
    name: LeaderName.Elagabalus,
    type: LeaderType.Ruler,
    reign: '218-222 AD',
    url: 'https://en.wikipedia.org/wiki/Elagabalus',
  },
  {
    name: LeaderName.SeleucusI,
    type: LeaderType.Ruler,
    reign: '305-281 BC',
    url: 'https://en.wikipedia.org/wiki/Seleucus_I_Nicator',
  },
  {
    name: LeaderName.SeverusAlexander,
    type: LeaderType.Ruler,
    reign: '222-235 AD',
    url: 'https://en.wikipedia.org/wiki/Severus_Alexander',
  },
  {
    name: LeaderName.Trajan,
    type: LeaderType.Ruler,
    reign: '98-117 AD',
    url: 'https://en.wikipedia.org/wiki/Trajan',
  },
  {
    name: LeaderName.Postumus,
    type: LeaderType.Ruler,
    reign: '260-269 AD',
    url: 'https://en.wikipedia.org/wiki/Postumus',
  },
  {
    name: LeaderName.LiciniusI,
    type: LeaderType.Ruler,
    reign: '308-324 AD',
    url: 'https://en.wikipedia.org/wiki/Licinius',
  },
  {
    name: LeaderName.Gallienus,
    type: LeaderType.Ruler,
    reign: '253-268 AD',
    url: 'https://en.wikipedia.org/wiki/Gallienus',
  },
  {
    name: LeaderName.MarcusAurelius,
    type: LeaderType.Ruler,
    reign: '161-180 AD',
    url: 'https://en.wikipedia.org/wiki/Marcus_Aurelius',
  },
  {
    name: LeaderName.AntigonusI,
    type: LeaderType.Ruler,
    reign: '306-301 BC',
    url: 'https://en.wikipedia.org/wiki/Antigonus_I_Monophthalmus',
  },
  {
    name: LeaderName.AntoninusPius,
    type: LeaderType.Ruler,
    reign: '138-161 AD',
    url: 'https://en.wikipedia.org/wiki/Antoninus_Pius',
  },
  {
    name: LeaderName.PinariusNatta,
    type: LeaderType.Moneyer,
    reign: '149 BC',
    url: 'https://en.wikipedia.org/wiki/Pinaria_gens',
  },
  {
    name: LeaderName.PhilipTheArab,
    type: LeaderType.Ruler,
    reign: '244-249 AD',
    url: 'https://en.wikipedia.org/wiki/Philip_the_Arab',
  },
  {
    name: LeaderName.TituriusSabinus,
    type: LeaderType.Moneyer,
    reign: '89 BC',
    url: 'https://en.wikipedia.org/wiki/Tituria_gens',
  },
  {
    name: LeaderName.YazidI,
    type: LeaderType.Ruler,
    reign: '680-683 AD',
    url: 'https://en.wikipedia.org/wiki/Yazid_I',
  },
  {
    name: LeaderName.QuintusTitius,
    type: LeaderType.Moneyer,
    reign: '90 BC',
    url: 'https://en.wikipedia.org/wiki/Titia_gens',
  },
  {
    name: LeaderName.Anonymous,
    type: LeaderType.Ruler,
  },
];
